name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest

    steps:
      - uses: actions/checkout@v4

      - name: Compila APK
        run: |
          # Imposta la variabile d'ambiente per evitare il blocco root interattivo di buildozer
          export BUILDER_ALLOW_ROOT=true
          buildozer --accept-root -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk












